-- MySQL Script generated by MySQL Workbench
-- Tue Jun 22 15:19:24 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id_usuario` TEXT NOT NULL,
  `empresa_nome_cnpj_email_endereco_telefone_descricao` TEXT NOT NULL,
  `clientefinal_nome_cpf_email_endereco_telefone_descricao` TEXT NOT NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produtos` (
  `produto_id` INT NOT NULL,
  `produto_nome_descricao_preco_cor_material_estoque` TEXT NULL,
  `usuarios_empresa_id` INT NOT NULL,
  PRIMARY KEY (`produto_id`, `usuarios_empresa_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`saida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`saida` (
  `id_saida` INT NOT NULL,
  `doado_nome_descricao_medidas_peso` TEXT NULL,
  `venda_descricao_quantidade_endereco` TEXT NULL,
  PRIMARY KEY (`id_saida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produtos_has_saida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produtos_has_saida` (
  `produtos_id_produto` INT NOT NULL,
  `produtos_usuarios_empresa_id` INT NOT NULL,
  `saida_id_doacao` INT NOT NULL,
  PRIMARY KEY (`produtos_id_produto`, `produtos_usuarios_empresa_id`, `saida_id_doacao`),
  INDEX `fk_produtos_has_saida_saida1_idx` (`saida_id_doacao` ASC) VISIBLE,
  INDEX `fk_produtos_has_saida_produtos1_idx` (`produtos_id_produto` ASC, `produtos_usuarios_empresa_id` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_has_saida_produtos1`
    FOREIGN KEY (`produtos_id_produto` , `produtos_usuarios_empresa_id`)
    REFERENCES `mydb`.`produtos` (`produto_id` , `usuarios_empresa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_has_saida_saida1`
    FOREIGN KEY (`saida_id_doacao`)
    REFERENCES `mydb`.`saida` (`id_saida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
